# Generated by Django 4.1.7 on 2023-02-17 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='datatime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 14, 57, 28, 662201)),
        ),
    ]
