# Generated by Django 4.1.7 on 2023-02-24 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_vendas_datatime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('cota', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('var_mercado_preco', models.FloatField()),
                ('var_preco_porcento', models.CharField(max_length=100)),
                ('ultimo_rendimento', models.FloatField()),
                ('proximo_rendimento', models.FloatField()),
                ('div_yield_mes', models.CharField(max_length=100)),
                ('div_yield_ano', models.CharField(max_length=100)),
                ('datatime', models.DateTimeField(default=datetime.datetime(2023, 2, 24, 16, 57, 28, 51877))),
            ],
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='nome_produto',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='vendedor',
        ),
        migrations.DeleteModel(
            name='Produtos',
        ),
        migrations.DeleteModel(
            name='Vendas',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
