# Generated by Django 4.1.7 on 2023-02-28 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ticket_remove_vendas_nome_produto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='name',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cota',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='datatime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 18, 17, 51, 59260)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='div_yield_ano',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='div_yield_mes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='proximo_rendimento',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ultimo_rendimento',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='var_mercado_preco',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='var_preco_porcento',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
