# Generated by Django 4.1.7 on 2023-03-02 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_ticket_datatime_alter_ticket_preco_mercado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='datatime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 2, 14, 28, 24, 816994)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='preco_mercado',
            field=models.FloatField(null=True),
        ),
    ]
